# These are supported funding model platforms
# github demon
issuehunt: # ReDemonnzz
otechie: # Demonzz
custom: # https://cdn.discordapp.com/avatars/784871460261855232/a_27092a52d6c92cf8c42039a446e80350.gif?size=4096
